import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { light } from './themes.js';
import baseStyles from './base.js';
import extraStyles from './extra.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Get color variables from themes
const colorVars = Object.keys(light).filter(k => k.startsWith('--'));

// 2. Get variables from base styles
const baseObj = baseStyles();
const rootBaseVars = Object.keys(baseObj[':where(:root)'] || {}).filter(k => k.startsWith('--'));

// 3. Get variables from extra styles
const extraObj = extraStyles();
const rootExtraVars = Object.keys(extraObj[':where(:root)'] || {}).filter(k => k.startsWith('--'));

// Merge and deduplicate
const allVars = [...new Set([...colorVars, ...rootBaseVars, ...rootExtraVars])].sort();

// Generate TypeScript content
const tsContent = `/**
 * Auto-generated by Clampography
 * TypeScript definitions for Clampography CSS Variables
 */

export type ClampographyVars = 
${allVars.map(v => `  | "${v}"`).join('\n')};
`;

const outputPath = path.join(__dirname, 'types', 'vars.d.ts');
fs.writeFileSync(outputPath, tsContent, 'utf-8');

console.log(`✅ Exported ${allVars.length} CSS variable types to src/types/vars.d.ts`);
