/**
 * Built-in Themes
 * 
 * Auto-generated by Clampography Dev Server.
 * Do not manually edit this file unless you know what you're doing.
 */

export const bubbles = {
  "color-scheme": "dark",
  "--clampography-background": "oklch(0.212 0.056 270.2)",
  "--clampography-border": "oklch(0.786 0.0 89.9)",
  "--clampography-error": "oklch(0.753 0.138 19.2)",
  "--clampography-heading": "oklch(1.0 0.0 89.9)",
  "--clampography-info": "oklch(0.683 0.154 255.7)",
  "--clampography-link": "oklch(0.661 0.151 242.1)",
  "--clampography-muted": "oklch(0.431 0.0 89.9)",
  "--clampography-primary": "oklch(0.554 0.127 252.0)",
  "--clampography-secondary": "oklch(0.52 0.138 326.8)",
  "--clampography-success": "oklch(0.706 0.125 171.9)",
  "--clampography-surface": "oklch(0.86 0.07 255.3)",
  "--clampography-text": "oklch(1.0 0.0 89.9)",
  "--clampography-warning": "oklch(0.971 0.186 109.4)",
};

export const dark = {
  "color-scheme": "dark",
  "--clampography-background": "oklch(10% 0 0)",
  "--clampography-border": "oklch(31% 0.03 254)",
  "--clampography-error": "oklch(63% 0.22 27)",
  "--clampography-heading": "oklch(98% 0.003 264)",
  "--clampography-info": "oklch(72% 0.17 254)",
  "--clampography-link": "oklch(72% 0.17 254)",
  "--clampography-muted": "oklch(68% 0.024 254)",
  "--clampography-primary": "oklch(63% 0.258 262)",
  "--clampography-secondary": "oklch(63% 0.25 300)",
  "--clampography-success": "oklch(65% 0.17 165)",
  "--clampography-surface": "oklch(12% 0 0)",
  "--clampography-text": "oklch(95% 0 0)",
  "--clampography-warning": "oklch(72% 0.17 65)",
};

export const light = {
  "color-scheme": "light",
  "--clampography-background": "oklch(100% 0 0)",
  "--clampography-border": "oklch(92% 0.003 264)",
  "--clampography-error": "oklch(63% 0.22 27)",
  "--clampography-heading": "oklch(15% 0.02 264)",
  "--clampography-info": "oklch(63% 0.258 262)",
  "--clampography-link": "oklch(43% 0.19 264)",
  "--clampography-muted": "oklch(52% 0.014 258)",
  "--clampography-primary": "oklch(63% 0.258 262)",
  "--clampography-secondary": "oklch(55% 0.28 300)",
  "--clampography-success": "oklch(65% 0.17 165)",
  "--clampography-surface": "oklch(96% 0.003 264)",
  "--clampography-text": "oklch(31% 0.02 257)",
  "--clampography-warning": "oklch(72% 0.17 65)",
};

export const themes = {
  "bubbles": bubbles,
  "dark": dark,
  "light": light
};

export const themesList = Object.keys(themes);
