/**
 * Built-in Themes
 * 
 * Auto-generated by Clampography Dev Server.
 * Do not manually edit this file unless you know what you're doing.
 */

export const broadcast = {
  "--clampography-background": "oklch(26.4% 0.000 89.9)",
  "--clampography-surface": "oklch(32.1% 0.000 89.9)",
  "--clampography-text": "oklch(90.9% 0.009 67.7)",
  "--clampography-heading": "oklch(100.0% 0.000 89.9)",
  "--clampography-primary": "oklch(82.7% 0.070 240.3)",
  "--clampography-secondary": "oklch(87.0% 0.066 284.0)",
  "--clampography-muted": "oklch(29.3% 0.000 89.9)",
  "--clampography-border": "oklch(100.0% 0.000 89.9)",
  "--clampography-link": "oklch(66.3% 0.073 241.4)",
  "--clampography-success": "oklch(78.5% 0.139 143.9)",
  "--clampography-warning": "oklch(97.4% 0.156 109.0)",
  "--clampography-error": "oklch(72.7% 0.169 28.7)",
  "--clampography-info": "oklch(82.6% 0.071 239.8)",
};

export const dark = {
  "color-scheme": "dark",
  "--clampography-background": "oklch(10% 0 0)",
  "--clampography-border": "oklch(31% 0.03 254)",
  "--clampography-error": "oklch(63% 0.22 27)",
  "--clampography-heading": "oklch(98% 0.003 264)",
  "--clampography-info": "oklch(72% 0.17 254)",
  "--clampography-link": "oklch(72% 0.17 254)",
  "--clampography-muted": "oklch(68% 0.024 254)",
  "--clampography-primary": "oklch(63% 0.258 262)",
  "--clampography-secondary": "oklch(63% 0.25 300)",
  "--clampography-success": "oklch(65% 0.17 165)",
  "--clampography-surface": "oklch(12% 0 0)",
  "--clampography-text": "oklch(95% 0 0)",
  "--clampography-warning": "oklch(72% 0.17 65)",
};

export const light = {
  "color-scheme": "light",
  "--clampography-background": "oklch(100% 0 0)",
  "--clampography-border": "oklch(92% 0.003 264)",
  "--clampography-error": "oklch(63% 0.22 27)",
  "--clampography-heading": "oklch(15% 0.02 264)",
  "--clampography-info": "oklch(63% 0.258 262)",
  "--clampography-link": "oklch(43% 0.19 264)",
  "--clampography-muted": "oklch(52% 0.014 258)",
  "--clampography-primary": "oklch(63% 0.258 262)",
  "--clampography-secondary": "oklch(55% 0.28 300)",
  "--clampography-success": "oklch(65% 0.17 165)",
  "--clampography-surface": "oklch(96% 0.003 264)",
  "--clampography-text": "oklch(31% 0.02 257)",
  "--clampography-warning": "oklch(72% 0.17 65)",
};

export const themes = {
  "broadcast": broadcast,
  "dark": dark,
  "light": light
};

export const themesList = Object.keys(themes);
