export const themes = {
  light: {
    "color-scheme": "light",
    "--clampography-background": "#ffffff",
    "--clampography-border": "#e5e7eb",
    "--clampography-error": "#ef4444",
    "--clampography-heading": "#111827",
    "--clampography-info": "#3b82f6",
    "--clampography-link": "#2563eb",
    "--clampography-muted": "#6b7280",
    "--clampography-primary": "#3b82f6",
    "--clampography-secondary": "#9333ea",
    "--clampography-success": "#10b981",
    "--clampography-surface": "#f3f4f6",
    "--clampography-text": "#374151",
    "--clampography-warning": "#f59e0b",
  },
  dark: {
    "color-scheme": "dark",
    "--clampography-background": "#0f172a",
    "--clampography-border": "#334155",
    "--clampography-error": "#ef4444",
    "--clampography-heading": "#f8fafc",
    "--clampography-info": "#60a5fa",
    "--clampography-link": "#60a5fa",
    "--clampography-muted": "#94a3b8",
    "--clampography-primary": "#3b82f6",
    "--clampography-secondary": "#a855f7",
    "--clampography-success": "#10b981",
    "--clampography-surface": "#1e293b",
    "--clampography-text": "#cbd5e1",
    "--clampography-warning": "#f59e0b",
  },
  retro: {
    "color-scheme": "light",
    "--clampography-background": "#ece3ca",
    "--clampography-border": "#cbbd99",
    "--clampography-error": "#c14b3a",
    "--clampography-heading": "#2c2420",
    "--clampography-info": "#5b8fa3",
    "--clampography-link": "#d97757",
    "--clampography-muted": "#756354",
    "--clampography-primary": "#e45f2b",
    "--clampography-secondary": "#f6c342",
    "--clampography-success": "#6b9f4f",
    "--clampography-surface": "#e0d6b6",
    "--clampography-text": "#4a3b32",
    "--clampography-warning": "#f6c342",
  },
  cyberpunk: {
    "color-scheme": "dark",
    "--clampography-background": "#000b1e",
    "--clampography-border": "#0f3661",
    "--clampography-error": "#ff0099",
    "--clampography-heading": "#ffffff",
    "--clampography-info": "#00f0ff",
    "--clampography-link": "#ff0099",
    "--clampography-muted": "#008f99",
    "--clampography-primary": "#fcee0a",
    "--clampography-secondary": "#05ffa1",
    "--clampography-success": "#05ffa1",
    "--clampography-surface": "#051630",
    "--clampography-text": "#00f0ff",
    "--clampography-warning": "#fcee0a",
  },
};

export const themesList = Object.keys(themes);
