name: Sync Dev Branch

on:
  push:
    branches:
      - v2

jobs:
  sync-branch:
    name: Merge v2 into dev
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: dev

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge v2 into dev
        run: |
          # Mergeuje nowości z v2 do aktualnie pobranej gałęzi dev
          git merge origin/v2 --no-edit
          # Wypycha zaktualizowaną gałąź dev na serwer
          git push origin dev
